services:
  # url-shortener:
  #   image: url-shortener:0.0.1
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8181:8181"
  #   restart: unless-stopped
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   env_file:
  #     - .env

  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "url_shortening"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d url_shortening"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_db:
